# Generated by Django 3.0.5 on 2020-04-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=200, verbose_name='Объект: ')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес: ')),
                ('date', models.CharField(max_length=200, verbose_name='Дата монтажа: ')),
                ('task', models.CharField(max_length=200, verbose_name='Задача: ')),
                ('jobs', models.CharField(max_length=200, verbose_name='Выполненые работы: ')),
                ('price', models.CharField(max_length=200, verbose_name='Общая стоимость проекта: ')),
                ('thumb1', models.ImageField(upload_to='static/img/project_img/', verbose_name='Миниатюра 1 (334x500): ')),
                ('thumb2', models.ImageField(upload_to='static/img/project_img/', verbose_name='Миниатюра 2 (334x500): ')),
                ('thumb3', models.ImageField(upload_to='static/img/project_img/', verbose_name='Миниатюра 3 (334x500): ')),
                ('thumb4', models.ImageField(upload_to='static/img/project_img/', verbose_name='Миниатюра 4 (1000x500): ')),
                ('thumb5', models.ImageField(upload_to='static/img/project_img/', verbose_name='Миниатюра 5 (500x1000): ')),
                ('thumb6', models.ImageField(upload_to='static/img/project_img/', verbose_name='Миниатюра 6 (500x1000): ')),
                ('img1', models.ImageField(upload_to='static/img/project_img', verbose_name='Изображение 1: ')),
                ('img2', models.ImageField(upload_to='static/img/project_img', verbose_name='Изображение 2: ')),
                ('img3', models.ImageField(upload_to='static/img/project_img', verbose_name='Изображение 3: ')),
                ('img4', models.ImageField(upload_to='static/img/project_img', verbose_name='Изображение 4: ')),
                ('img5', models.ImageField(upload_to='static/img/project_img', verbose_name='Изображение 5: ')),
                ('img6', models.ImageField(upload_to='static/img/project_img', verbose_name='Изображение 6: ')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
