# Generated by Django 3.0.1 on 2020-05-04 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_recall'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=200, verbose_name='Почта')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Заявка на каталог',
                'verbose_name_plural': 'Заявки на каталог',
            },
        ),
    ]
