# Generated by Django 3.0.1 on 2020-05-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_sendcatalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendCatandprice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('mail', models.CharField(max_length=200, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Заявка на котолог и прайс',
                'verbose_name_plural': 'Заявки на каталог и прайс',
            },
        ),
    ]
