# Generated by Django 3.0.1 on 2020-05-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_sendcatandprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendcatandprice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
    ]
